version: "3.7"
services:
  database:
    image: "postgres:13"
    container_name: mobapp-database
    restart: on-failure
    ports:
      - 5432:5432        
    environment:
      POSTGRES_DB: ${DB_BASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    volumes:
      - database-data:/var/lib/postgresql/data

  api:
    container_name: mobapp-api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 8080:8080
      - 8181:8181
      - 4848:4848
    depends_on:
      - "database"
    environment:
      DB_HOST: mobapp-database
      DB_BASE: ${DB_BASE}
      DB_USER: ${DB_USER} 
      DB_PASSWD: ${DB_PASSWD}

volumes:
  database-data:
